language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
    ./fixNodeModules.sh
    npm i -g codecov
# safelist
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ #vX.Y
